### ISSUE TITLE
Work out what signs are required around the venue

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#101]
We'll need signs for the following:
- PythonAnywhere room (CC1.3)
- Osper Room (CC1.4)
- YPlan Room (CC1.8)
- LaterPay Room (CC2.1, Friday)
- The Software Sustainability Institute Room (CC2.1, Saturday & Sunday)
- LaterPay Learning Space (the Bistro)
- Sprint room(s)
- DjangoGirls
- TransCode
- Teachers' CPD room(s)
- PyKids room(s)

What have I missed?

**Comment by holdenweb** [comment]
Arrowed signs from the registration desk so that anyone can find their way to any room from there just by following signs? If someone points me at a map I could work out the necessary branching structure

**Comment by moonmar** [comment]
To Registration

**Comment by inglesp** [comment]
@holdenweb, that's a good idea.

@zeth / anyone, do we have a map of the venue?

**Comment by zeth** [comment]
Two signs for overflows with the following text:

First Class
(Overflow)

[Feel free to be more creative or witty.]

**Comment by zeth** [comment]
No floor plan. I just have this list of rooms:
http://www.coventry.ac.uk/business/conference-facilities/technocentre/room-planner/

The main thing is most of the rooms are obvious to find, the ones that are not are:

LaterPay Room (CC2.1, Friday)
The Software Sustainability Institute Room (CC2.1, Saturday & Sunday)
LaterPay Learning Space (the Bistro)

Especially CC2.1 will need signage from the area outside CC1.3.

**Comment by moonmar** [comment]
I think I have something at home.  Will look tonight.

**Comment by moonmar** [comment]
I have some plans.  How do I put them here?

**Comment by moonmar** [comment]
Unfortunately, we don’t support that file type.  Try again with a PNG, GIF, JPG. - ha ha.  They are PDFs.

Ideas please folks.

**Comment by moonmar** [comment]
I've committed the plan to https://github.com/PyconUK/planning2015/blob/master/TCConfrencePlans.pdf

**Comment by inglesp** [comment]
Signs have been made.
