### ISSUE TITLE
Make signs

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#102]
Once we've established what signs we need for the conference (see https://github.com/PyconUK/planning2015/issues/101), somebody will need to make them.

**Comment by holdenweb** [comment]
We can print A3 color here at work, so I should be able to handle that if the specification is ready soon.

**Comment by moonmar** [comment]
Thanks for that Steve.  Is there a Github issue around this?  That might be
a good way of managing who is doing what for signage.

It also raises the question of equipment for the reception desk.  I have a
laptop that can be used but we will need a printer, you can guarantee it.
Previously we had the facilities provided by Thyme.

Shall I print my ink jet or should we just buy a printer from PC World and
some cartridges?

_Mary_
_Mobile_ - +44 (0) 7857 373727

**Comment by holdenweb** [comment]
Not aware of an issue, but feel free to start one.

I'd suggest we buy a printer, then either raffle it off or give it away as
a door prize.

I'm also planning to bring my ticket printer of on-site badge-making.

S

On 5 September 2015 at 16:27, Mary Mooney notifications@github.com wrote:

> Thanks for that Steve. Is there a Github issue around this? That might be
> a good way of managing who is doing what for signage.
> 
> It also raises the question of equipment for the reception desk. I have a
> laptop that can be used but we will need a printer, you can guarantee it.
> Previously we had the facilities provided by Thyme.
> 
> Shall I print my ink jet or should we just buy a printer from PC World and
> some cartridges?
> 
> _Mary_
> _Mobile_ - +44 (0) 7857 373727
> 
> On 4 September 2015 at 13:24, Steve Holden notifications@github.com
> wrote:
> 
> > We can print A3 color here at work, so I should be able to handle that if
> > the specification is ready soon.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/PyconUK/planning2015/issues/102#issuecomment-137721542>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/planning2015/issues/102#issuecomment-137967538
> .

## 

Steve Holden
Senior Developer Advocate

**Comment by inglesp** [comment]
@moonmar / @holdenweb -- there is an issue, and you've both commented on it by replying to the notification emails!

If we don't have a printer then I can see that it'd make sense to buy one, but bringing one from home is going to be less work.  @moonmar, are you sure you're happy for us to use yours?

**Comment by inglesp** [comment]
@holdenweb's made some super signage and has shared with the mailing list -- hurrah!

**Comment by holdenweb** [comment]
Glad you think it's super

On 16 September 2015 at 18:20, Peter Inglesby notifications@github.com
wrote:

> Closed #102 https://github.com/PyconUK/planning2015/issues/102.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/planning2015/issues/102#event-411206146.

## 

Steve Holden
Senior Developer Advocate
