### ISSUE TITLE
Equipment for Education Track/Raspberry Pis

### ISSUE THREAD

**Issue by moreati** [PyconUK/planning2015#106]
### Requirements

| Required | Item | Present | Comments |
| --: | --- | --: | --- |
| 100 | Power sockets (50 pi, 50 monitor) | 176 | 54 on reels, 122 on ext. leads |
| 30 | Keyboards | 4 |  |
| 30 | Mice | 1 |  |
| 50 | USB power supplies | 0 |  |
| nn? | Monitors | 6 |  |
### Shopping list
- [x] 30 mini keyboards
- [x] 30 mice
- [x] 50 USB power supplies (1A or better)
- [ ] nn HDMI monitors?

**Comment by ntoll** [comment]
Please add gaffer tape and ties to keep the electrical wires under control.

Also, we do have some (10?) monitors somewhere (Zeth????).

The PSU should be capable of running a RPi.

Yay... many many many thanks!

**Comment by moonmar** [comment]
Alex

Is the list of existing stock listed. It seems Nicholas is asking for more monitors, or perhaps not

**Comment by ntoll** [comment]
I'm saying that PyCon UK own some monitors and they're not listed here. Do we know where they are? If so, I'd like to use them :-)

**Comment by moreati** [comment]
6 monitors are listed here, note the 3rd column. Are you saying there's more than 6?

**Comment by moreati** [comment]
@ntoll ping

**Comment by moreati** [comment]
Front runner so far is ModMyPi

| Product | Qty | Price | Total (ex VAT) |
| --- | --: | --: | --: |
| [Power Supply - UK Plug 5V 2A](https://www.modmypi.com/raspberry-pi/accessories/power-supplies/power-supply-uk-plug-5v-2a) | 50 | £4.16 | £249.48 |
| [White 3 Button Optical Mouse with Scroll Wheel - Wired USB](https://www.modmypi.com/raspberry-pi/accessories/keyboards-and-mice/white-3-button-optical-mouse-with-scroll-wheel-wired-usb) | 30 | £1.66 | £59.69 |
| [Basic Keyboard Wired USB](https://www.modmypi.com/raspberry-pi/accessories/keyboards-and-mice/basic-keyboard-wired-usb) | 30 | £3.33 | £119.70 |
|  |  | Total (ex VAT) | £357.39 |
|  |  | **Total (inc VAT)** | **£428.87** |

I've gone for:
- Spend a bit more on Pi branded, 2 Amp PSUs - for reliability/flexibility.
- Attached (i.e. not separate) cables - one less thing to go lose or go walkies
- Full size keyboards, because they're half the price of mini keyboards

@ntoll 
1. Do you need more than the 6 monitors that we have?
2. Do you have a motivation for mini keyboards? Other than reducing storage space?

**Comment by ntoll** [comment]
@moreati pong

Monitor situation OK.

We just need keyboards... I only said "mini" for storage reasons.

**Comment by moreati** [comment]
@moonmar are you happy to place the above order (the links go directly to the products in question), or would you prefer I did?

To remove any chance of miscommunication. We need the mice, the keyboards and the power supplies. Nicholas's previous comment is clarify that any type of keyboard will do - they don't have to mini.

**Comment by moreati** [comment]
These have been ordered, they should arrive at the Technocenter on Monday or Tuesday. At Mary's request I switched the full size keyboards to compact ones.

**Comment by moreati** [comment]
These have shipped, tracking info: http://www.dhl.co.uk/content/gb/en/express/tracking.shtml?AWB=9475527946&brand=DHL
