### ISSUE TITLE
Property of PyCon UK Society stickers

### ISSUE THREAD

**Issue by moreati** [PyconUK/planning2015#107]
We're buying a lot of kit, we should mark it as belong to us. I'm not suggesting anything like holograms, ~~or serial numbers~~.

Just something that'll stay stuck and say:

> Property of PyCon UK Society
> If found please contact xxxx yyyyy

Edit: It's hard to find asset labels that don't come with serial numbers/barcodes.

**Comment by moreati** [comment]
Bookmarking http://www.patlabel.co.uk/asset-labels-appliance-property-colours-p-129.html

**Comment by moreati** [comment]
@moonmar What do you think of getting asset labels for the kit? The cost would be £25 for 1000 with our name, contact details (e.g. a telephone number or email address) and a unique serial/barcode. We don't have to use the barcodes, but they cost the same regardless.

**Comment by moonmar** [comment]
I think that would be a splendid idea.  We have spent in excess of £2k so far, not including the equipment stored from previous years.

**Comment by moreati** [comment]
Is there an existing telephone number for the society? One that'll be around and able to ring a year or 2 years from now? Would reusing one of the CoC numbers be appropriate?

Plan B: I'll put https://www.pyconuk.org in the telephone field

**Comment by moonmar** [comment]
There is no reason why we can't use the CoC number ending 1565. It is our phone after all.

**Comment by moonmar** [comment]
Sorry that's it imei number. 07743 352447

**Comment by moonmar** [comment]
Number posted

**Comment by moreati** [comment]
Labels ordered, I'll bring them on Thursday
