### ISSUE TITLE
Discuss post-conference storage

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#108]
From an email from Mary:

"Can you put up an issue for me about storage post conference.  We need to talk about it.  We are purchasing a lot of valuable equipment and need somewhere safe to store it before the next conference.

I am happy to seek quotations for a storage bin, if that is way we decide."

**Comment by moonmar** [comment]
Well Sheila and I hope to be going home around 2pm this afternoon.

We have an AWFUL lot of stuff.  Some of it quite valuable.

Tim has suggested he takes the high value items and stores them until we decide where all our stuff needs to go.

We need to find a home for the rest:

gang sockets
monitors
keyboards
mice
and other stuff
I can put them up temporarily in my garage.  I am thinking of returning the garage to the Council in the near future so this is not a long term fix.

Alternatively we could hire a store room locally and put everything in so we all know where it is. It would also be insured (something it wouldn't be in my garage which is 20 houses away from where I live).  I could try and find somewhere for tomorrow and pick it up and move it then.

Suggestions, directions, ideas please.

**Comment by moonmar** [comment]
Sorted. We have contracted for four weeks at Coventry SafeStore.  Will relocate to a smaller locker at the end of the 4 weeks.
