### ISSUE TITLE
Where to put all the stuff on Monday!

### ISSUE THREAD

**Issue by moonmar** [PyconUK/planning2015#109]
We have bought a lot of stuff for this conference.  

It could return to the Minworth garage - but that is not the safest place for valuable equipment.

Are people happy for me to find a local store place, signing up perhaps for six months?

**Comment by inglesp** [comment]
Sounds sensible -- what would it cost?

**Comment by moonmar** [comment]
I will do a search for prices sometime between now and Sunday.
