### ISSUE TITLE
Share plans for science track

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#11]

**Comment by snim2** [comment]
Should this be done via these Issues?

**Comment by inglesp** [comment]
No, I think we should still use the mailing list for this kind of thing, at least until everyone's got the hang of Issues.

**Comment by inglesp** [comment]
@snim2, it'd be good to have some text for http://www.pyconuk.org/science/ as soon as possible.  Can you either submit a pull request to the site, or send some text to the mailing list?
