### ISSUE TITLE
Stuff the swag bags

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#110]
We're expecting the following to be delivered to the venue for the swag bags:
- Abilisoft/Cobe.io: stickers and flyers
- HP: USB drives
- Nephila/Divio: notebooks and flyers (not for the children), and stickers (for everyone)
- Osper: "some stuff"
- PythonAnywhere: pens, in a box labelled "Promotional Pen Site"
- YPlan: shirts and flyers, arriving Thursday afternoon

Flyers should probably not be put into the children's bags, except possibly Osper whose product is aimed at young people.  Judgement will have to be applied here.

In addition, Pluralsight are sending some stuff but this is for their booth and should not be stuffed into swag bags.

If there is anything else that looks like it might be swag, please ask me before doing anything with it!

**Comment by snim2** [comment]
I have some swag for the SSI room. This is an SSI zip stand, SSI leaflets and stickers and Overleaf swag. I will bring this along and put it in the room on Friday night / Sat morning.

**Comment by inglesp** [comment]
There was some super stuffing this evening, thanks everyone.
