### ISSUE TITLE
Start discussion about applications to PSF for funding

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#17]

**Comment by ntoll** [comment]
This page: https://www.python.org/psf/grants/ states that we can
expect $10 per regular attendee and $50 per person attending an
education track.

Given around 300 regular attendees and at least around 150 on the
education track (including DjangoGirls, TransCode) that gives the
following estimated figures:

300x10=$3000
150x50=$7500
TOTAL =$10500

(that's around £7000)

Finally, there is also the new PSF sponsorship mechanism that you'll
have noticed I've emailed Van about so we can officially request
sponsorship funds.
