### ISSUE TITLE
[Proposal] Traffic light fast-feedback system for talks

### ISSUE THREAD

**Issue by doismellburning** [PyconUK/planning2015#23]
Have just spent the day at [PipelineConf](http://pipelineconf.info/). In the spirit of continuous delivery and a tight feedback cycle, attendees were all given post-its in their swag bags when they turned up - a small stack of red, yellow and green ones. At the end of each talk, someone stood by the door with a box, and people were asked to drop a post-it in as feedback. They could comment with more detail if they wished, or just give basic "dislike / neutral / like".

Thoughts?
- Increases the effort requirement - need someone at each exit, need to distribute post-its
- Means every talk gets some level of immediate audience feedback, vs "maybe someone mentions it in the post-conference survey"

**Comment by holdenweb** [comment]
One year PyCon US used tokens, to be dropped in a good/bad/indifferent box. Then they had to be weighed. It was a total mess, and made far too much work. Anything that requires counting tokens of any kind is bound to be a bit painful.

Oddly enough, speaker and talk quality correlate positively with attendance, in general. So if we want to capture information about speaker desirability the best way to do this is to count the attendance at each talk - but that gives feedback to the organizers, not the speaker, really, so may not be what you want.

**Comment by zeth** [comment]
Europython often has clever automated ways of dealing with over-subscribed talks and generating repeats. Obviously ours is a much shorter conference, but it is worth thinking about what data we ask the session chairs to record and what we do with it.

**Comment by inglesp** [comment]
I like the idea but I think this is going to be one thing too many to organise.

If somebody wants to make this happen then please re-open the issue!
