### ISSUE TITLE
Hack something together for SMS messaging

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#26]

**Comment by holdenweb** [comment]
What's required? Something to send text messages to all registered delegates?

**Comment by lukestanley** [comment]
Yes  - to take output peoples numbers from the ti.to - the new ticketing / payment solution and loop over them or similar with Twilio.
Even CSV export could work.
@ntoll Is there a login or something I should have? I signed up with my usual email address on https://ti.to/signup

**Comment by ntoll** [comment]
For the record, Daniele is the person for Ti.To signups. :-)

**Comment by lukestanley** [comment]
@evildmp I signed up to Ti.to and I need my account to pull phone numbers from CSV, or the some other way through the API. lukestanley is probably my user name. Can you sort my access out?

**Comment by moonmar** [comment]
Hi Luke

I have just been into ti.to and under the Attendees tab I got the option to
export to CSV etc.

_Mary_
_Mobile_ - +44 (0) 7857 373727

**Comment by inglesp** [comment]
@lukestanley, what's going to happen with this?

**Comment by lukestanley** [comment]
I have:
-Coded this: https://github.com/PyconUK/sms_conference
-Tito access to download CSV file
-Setup a paid Twillio account with $20 of credit, linked to my bank account

I can set this up on a designated computer at the conference, and tell core organisers about it. 
I can send Mary an invoice for credit used.

**Comment by inglesp** [comment]
Hi @lukestanley -- have just had a look at this and it looks like the code will do what it says on the tin.

The next steps are to work out when this would need to be used, as well as how we would make use of it if we did need to use it.

**Comment by lukestanley** [comment]
It was built as a solution for if there was a schedule change to notify people but there are obviously other things it could be used for.
It could be handy for other announcements too.

**Comment by inglesp** [comment]
Something's hacked together -- thanks @lukestanley -- so I'm going to close this.
