### ISSUE TITLE
Invite DjangoGirls organisers to mailing list

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#29]

**Comment by inglesp** [comment]
I'm not aware of this having been done.  @ntoll, as you've been in touch with them about this, can you follow up?

**Comment by ntoll** [comment]
I've done this and followed it up with an email a couple of days ago to say I was going to sign them up to the admin list. That they have not replied to confirm is worrisome. Will send out an email right now. Don't want to appear spammy.

**Comment by ntoll** [comment]
OK... follow up email sent. I'll close this ticket when I get a response.

**Comment by ntoll** [comment]
OK... I've been in touch with DG and after an excellent meeting IRL the issue was left unresolved. Damn.

**Comment by ntoll** [comment]
I'll close this issue since the DG prefer to communicate via email to me. :-/
