### ISSUE TITLE
Investigate the creche

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#31]

**Comment by inglesp** [comment]
We're going to offer a creche on the registration form, and work out what we need to provide based on that.  I'm going to keep this issue open, but change the milestone, so that we don't lose sight of it!

**Comment by ntoll** [comment]
+1 - it's all on the ticket form. We can book something end of July once we have a handle on the numbers.

**Comment by inglesp** [comment]
We've got a creche.
