### ISSUE TITLE
Talk about Pycon UK at Pycon in Montreal

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#32]

**Comment by holdenweb** [comment]
Who all is planning to be in Montreal (besides me)? We should give a lightning talk at least, and hopefully maybe an open space session as well, right? I'll be happy to collaborate on that.

**Comment by ntoll** [comment]
I'm there. The plan is that I give a lightning talk about PyconUK and specifically the education track as part of the education summit.

N.

**Comment by holdenweb** [comment]
Cool. See you there.  S

On Mar 25, 2015, at 11:27 AM, Nicholas Tollervey notifications@github.com wrote:

> I'm there. The plan is that I give a lightning talk about PyconUK and specifically the education track as part of the education summit.
> 
> N.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Steve Holden steve@holdenweb.com / +1 571 484 6266 / +44 113 320 2335 / @holdenweb

**Comment by inglesp** [comment]
I assume this has been done -- if not, it's too late!

**Comment by ntoll** [comment]
It was done - twice!
