### ISSUE TITLE
Start discussion about registration/info desk requirements

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#33]

**Comment by inglesp** [comment]
This can wait until closer to the event.

**Comment by zeth** [comment]
Renamed due the fact that it is all going to be in the restaurant now.

**Comment by inglesp** [comment]
@snim2 / @zeth, what else needs to happen here?

**Comment by moonmar** [comment]
Need to organise boxes to put the badges in.  Not having personal names on mugs is going to make life a lot easier.

Could have a separate table for the swag bags.

Tshirts will be issued on separate desk, probably by Sheila the Personal Shopper to the Pycon Community.  She will need someone to help.

Young Person reception will be in main Reception on Saturday, OIC Suki Kaur (a YP parent who has volunteered).

**Comment by inglesp** [comment]
@moonmar, this looks good.

@ntoll's finding some community volunteers to set up the info desk, and to staff it during registration, and they can be pointed at this issue.

Do we need to make sure that there's always a member of the committee on hand at the info desk?
