### ISSUE TITLE
Find ISO John wanted to share with us

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#40]

**Comment by zeth** [comment]
Was it Debian? Did he put lots of Python tools on the DVD? I know he was keen that Python users should consider supporting the open source world more generally, including the free software desktop.

**Comment by lukestanley** [comment]
I don't think it was Debian, but probably was Debian based. I have a
command I'd like to have ran on John's systems to try finding it, the
details have been sent to you Zeth.
If we can't find it, or in addition we could do a group vote on the best
Python distros or such for the conference, or as an ongoing thing.
--Luke

**Comment by nceder** [comment]
Contacted, heard back from PyLadies London and Brighton... will pursue others one more time

**Comment by ntoll** [comment]
Do we really need this..? People are quite picky about the OS they use so are likely to ignore anything we suggest. What exactly was John trying to achieve..? If there's nothing happening for this may I suggest we close this issue..?

**Comment by lukestanley** [comment]
I have a find command that sorts by date that I asked to be ran. I'm happy to go over there sort it with @zeth or Robert.

**Comment by inglesp** [comment]
@lukestanley, is anything going to happen here?
