### ISSUE TITLE
Contact PyLadies chapters around UK

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#41]

**Comment by nceder** [comment]
Emails sent on 21/04/15 to organisers of PyLadies London & Edinburgh, Django Girls London & Edinburgh, cc Ola Sitarska.

**Comment by inglesp** [comment]
Hurrah @nceder -- unless there's anything else you think we need to do on this issue, close at will!

**Comment by nceder** [comment]
I'd keep it open to record responses as they come in... unless you think that's too much record-keeping?

**Comment by ntoll** [comment]
If anything, we need to record all this. I'm desperate to move away from the "it was all in John's head" model of conference organisation. ;-)

**Comment by nceder** [comment]
Contacted, heard back from PyLadies London and Brighton... will pursue others one more time

**Comment by nceder** [comment]
Indeed, I've been in touch with Becky already. :-)

On 25 May 2015 at 05:50, Dougal Matthews notifications@github.com wrote:

> /cc @rebkwok https://github.com/rebkwok
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/planning2015/issues/41#issuecomment-105125017
> .

## 

Naomi Ceder
https://plus.google.com/u/0/111396744045017339164/about

**Comment by d0ugal** [comment]
Oh, good! I thought you might have but wanted to check. Sorry for the noise!
