### ISSUE TITLE
Suggest sponsorship actions and checklists

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#43]

**Comment by snim2** [comment]
I think the Google Docs document has a list of these now, so this can be closed?

**Comment by ntoll** [comment]
This was all done at the beginning of last month. I'll close this with a reference to the Google doc here: https://docs.google.com/spreadsheets/d/1t-EjwN5-cyy2zeA_eTI5YTs1fmMvkZz6K4Ip00rvd3s/edit#gid=0
