### ISSUE TITLE
Food Provision

### ISSUE THREAD

**Issue by ntoll** [PyconUK/planning2015#46]
We need to have a clear understanding of the catering requirements for the conference including estimates for numbers. Someone (me) should put this in an obvious place for everyone to see and be in touch with the venue to ensure they have a clear understanding of what food needs to be where at what time.

Off the top of my head these are:
- Python Beer from Fuzzy Duck.
- Breakfasts on Friday, Saturday, Sunday and Monday.
- Tea/Coffee breaks on Friday, Saturday, Sunday and Monday.
- Lunch on Friday and Saturday.
- A roast lunch on Sunday.
- Sandwiches for Monday's sprint lunch.
- An assumed corkage cost for Friday evening social / charity event.
- Nibbles for a PSF members / PyconUK organiser's reception late Saturday afternoon.
- Saturday evening conference meal.
- Mid morning snacks for the kids in the education track.
- Mid-morning tea/coffee for parents in the education track.
- Sandwich packed lunch for the kids and parents in the education track.

**Comment by moonmar** [comment]
A parent from last year has suggested that even though the sponsorship covered the young people costs, if we ask for a contribution from parents for food at least they know they are going to be fed as well.

**Comment by moonmar** [comment]
Tea/Coffee breaks on Friday, Saturday, Sunday and Monday.

This has been changed to beverages available (main conference adults) all the time.  To prevent a rush at break times.

**Comment by ntoll** [comment]
These issues have been addressed in the recent meeting at the Techno Centre which was written up via email.
