### ISSUE TITLE
Correspondance Address for PyconUK Society

### ISSUE THREAD

**Issue by ntoll** [PyconUK/planning2015#47]
To quote Mary, "I know the correspondence address is John's office but I doubt anyone else does."

Is this correct..? What happens when Thyme moves out..?

**Comment by moonmar** [comment]
We will move the address before they move.  Currently searching for a suitable alternative.

**Comment by zeth** [comment]
Thyme are planning to keep a virtual office at the technocentre, mail will still be received and available there for as long as we want.

**Comment by zeth** [comment]
Probably need a new address if/when we pick a bigger venue. I am happy to volunteer my address if no one has a better plan.

**Comment by moonmar** [comment]
I think it would be better to have an "office" address.  Individuals have a
tendency to take holidays, which may make prove problematic to get mail.

M

**Comment by moonmar** [comment]
Addressed changed to Services for Education Birmingham 1 care of Tim Williams.
