### ISSUE TITLE
Detailed plans for handling CoC issues

### ISSUE THREAD

**Issue by snim2** [PyconUK/planning2015#48]
Nearer the time we should close this issue once we have:
- a rota of people to handle CoC issues during the conference
- a decision on whether we need extra phones and if so a plan for getting some and putting credit on them
- a plan for how to brief other volunteers on CoC issues
- a plan for how to make sure attendees know what to do in the event of a problem
- a plan for how to raise the CoC in the opening plenary
- a Hangout / appear.in for the CoC group to discuss how to handle issues in more detail
- a clear protocol for what we do if an issue comes up. This has already been discussed, but needs  dissemination. What we discussed was:
  - Volunteers should know how to contact the CoC team and at least a couple of us should always reachable during the conference. 
  - If an issue is raised with another volunteer it should be passed on to someone in the CoC group
  - Volunteers should commit to keeping all issues completely confidential (unless authorities need to be involved). 
  - In deciding how to handle a complaint, ideally all members of the CoC group should be involved in a decision. If a decision needs to be made very quickly for some reason, no one should take a decision alone.

**Comment by moonmar** [comment]
a decision on whether we need extra phones and if so a plan for getting some and putting credit on them

We have four Moto E's from last year.  It will be easy enough to put credit on them.  I have also added my "running MP3 phone" to the housekeeping notes.  It is a payg phone.

**Comment by zeth** [comment]
> a plan for how to raise the CoC in the opening plenary.

Either will need some exact text, a specific slide or someone to call up. If the latter, it needs to be quite snappy as the opening plenary has many many notices.

**Comment by zeth** [comment]
I think it is best that in the opening plenary I read directly from here:
http://www.pyconuk.org/codeofconduct/

**Comment by moonmar** [comment]
We have two mobile numbers for the CoC now

0793 373 7922; and

0774 335 2447

**Comment by inglesp** [comment]
@snim2, thanks for the clear outline of what we need to do here.

This task doesn't have an owner, so I'm assigning to you.

**Comment by inglesp** [comment]
The original issue mentions "a Hangout / appear.in for the CoC group to discuss how to handle issues in more detail".

@snim2, can you schedule this?

**Comment by snim2** [comment]
Ok, will do

**Comment by inglesp** [comment]
Hi @snim2 -- is this going to happen?

If not, I'd really like to have a short meeting tomorrow or first thing Friday morning to discuss how we're going to handle any conduct complaints.  At the moment, I'm not really sure what would happen if somebody does make a complaint or raise a concern about conduct.

**Comment by snim2** [comment]
Sorry, I let this slip. If enough of us are around tomorrow evening that would be best, then we can brief the other volunteers on Friday.

**Comment by inglesp** [comment]
This has been done off list.
