### ISSUE TITLE
Note to self. AGM script from email

### ISSUE THREAD

**Issue by zeth** [PyconUK/planning2015#49]
PyConUK is itself the annual general meeting of the PyCon UK
society. Welcome to the formal AGM part of PyCon UK 2013, we will try
to be prompt. If we take more than 5 mins of your time it would be
very disappointing.

We will have a report from the chairman, a report from the treasurer
and a vote on whether to re-elect continuing committee members.

John is at another session so I will give his report on his behalf.

"We decided to organise a conference, we planned a conference and we
delivered a conference. Once again we failed to organise additional
smaller events as aimed for by part 2 ii of the constitution."

[ASK DELEGATES FOR THEIR IDEAS ON OTHER EVENTS THAT COULD BE HELD,
MENTION PYBOATUK]

[REPORT FROM TREASURER HERE, IN PERSON OR READ OUT (I.E. A QUICK
STATEMENT OF WHETHER WE BROKE EVEN OR NOT.]

We will now seek to reelect the continuing committee members as a
block.

New committee members are co-opted by the committee and do not need to
be voted upon, the exact roles that the members take also is decided
by the committee, and we will ensure there is a chairperson,
vice-person, treasurer and secretary. Also note that:

"The Committee shall be composed of a minimum of four persons and a
maximum of ten persons."

If the continuing members are re-elected as a block then the AGM is
finished. If the vote fails it is more complicated see the
constitution.

It is important to understand that the PyConUK Society committee is
only one subset of the organising team and at-conference
crew. Membership of the committee is not required for organising,
leading events or voting at organisational IRC meetings.

In order to vote, a delegate must be a paid up member of the PyConUK
society. The membership fee is the first pound of the conference
ticket. Anyone given free entry either must not vote or must give the
society treasurer £1. Membership of the society is not compulsory and
anyone who does not want to be a member can tell the treasurer and
from membership and the society gives the £1 to charity instead.

[ASK IF ANYONE NEEDS TO JOIN THE SOCIETY, COLLECT A POUND FROM THEM IF
THEY DO]

We need to appoint someone not on the board to chair the election,
count and declare the result.

[ASK FOR A VOLUNTEER NOW, BRING THEM TO THE STAGE. FUZZYMAN OR JF NORMALLY WILLING]

[ASK IF ANYONE IS CONFUSED]

[COMMITTEE RESIGNS AND ELECTION CHAIR TAKES OVER]

**Comment by moonmar** [comment]
I have never received any £s from members.  Shouldn't we do this with a paper form?

**Comment by zeth** [comment]
I assume you mean for people who didn't buy a ticket? Well the main thing is speed. but I guess I could mention the form on the day before?

**Comment by inglesp** [comment]
@zeth, now we've got https://github.com/PyconUK/PyConUKSociety, is there anything we need to do here?
