### ISSUE TITLE
Move useful information from wiki to site

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#60]

**Comment by inglesp** [comment]
The only thing I can see that we have on the wiki but not on the website is the FAQ, which is out of date.

@zeth, do you want to do anything with this?

**Comment by snim2** [comment]
- I'm not sure all the accommodation stuff moved over.
- Is there a way to see a list of every page on the wiki, so we can check?

**Comment by inglesp** [comment]
Looks to me like the only information we're missing from the accommodation page is about couch surfing, and it's probably too late to do anything useful here.

I've got no idea how to see a list of every page on the wiki -- I'm getting `FullSearchCached: execution failed [20] (see also the log)` errors when I try to list all the categories.

Given that we've not had any questions from delegates that could/should be answered on the website, I'm going to assume that we've got enough useful information on the website.

**Comment by snim2** [comment]
I think the only question remaining is whether it is worth moving this to Planning 2016, if there is information on the old wiki (for example the historical records of all previous PyCon UKs) that people would like to keep somewhere / somehow. In which case, this might make a good Sprint problem...
