### ISSUE TITLE
Create a list of to-be-designed assets

### ISSUE THREAD

**Issue by hawkz** [PyconUK/planning2015#63]
I need a list (or assigned ticket) with what artwork is needed, ideally with the size it'll be printed/displayed at, and the lead time on getting it sent off (thinking t-shirts / merch especially).

Come at me!

**Comment by inglesp** [comment]
@hawkz, anything else you need here?

**Comment by hawkz** [comment]
I don't think anyone else needs anything at this unless we wanted to pre-plan 2016... so we're likely all good.
