### ISSUE TITLE
Submit proposal for PSF funding of Trans*Code

### ISSUE THREAD

**Issue by ntoll** [PyconUK/planning2015#65]
To be done with @ntoll.

**Comment by nceder** [comment]
PSF guidelines are $50 per person where there is 6 hours or more of Python instruction, $10 a head for conferences, and unspecified for hack days. 

Keeping this in mind, I'd suggest we apply for support for Django Girls from the PSF and pool the money from that and sponsorship to support both Django Girls and Trans Code.

**Comment by ntoll** [comment]
Sounds like a plan! This is also linked with issue #66. I guess there are two emails to send (one for each issue). 

Given the expected numbers we have and the way the PSF buckets up funds I guess we could be asking for the following:
- 30 x $50 ($1500) for the Django Girls
- 40 x $50 ($2000) for the teacher's track
- 100 x $50 ($5000) for the kids track
- 300 x $10 ($3000) for the other delegates

Total PSF support = $11,000

Blimey. What's the worse that could happen..?

**Comment by nceder** [comment]
That's a lot, but there is a lot going on - we'd probably want to make that clear. I have no idea if they'll fund all of it. 

In any case, I think they will want to know somewhat specifically what the money for the last three items will be supporting - meals? admission? venue? etc... (Django Girls I think they know it would be full tickets, but it wouldn't hurt to make whatever it is clear).

**Comment by ntoll** [comment]
It is a lot. For each of the final three items the cost breakdown would be:
- Teacher's track. We only have funding for the cover of the supply teachers. PyConUK is swallowing the cost of the teacher's reduced rate tickets. The $50 per teacher would bring us closer to our "at cost" ticket for each teacher.
- Kids track. To be honest, we only have support for the kids track to the extent that it covers the cost of the venue hire. We're providing them and their parents with a picnic lunch (we're making it so it only costs £5 per child to attend) - this will need paying for. Also, we're likely to incur other costs related to the kids' day such as equipment hire/purchasing and covering the costs of the people running the workshops (they're currently going to have to buy a conference ticket!).
- The money for the other delegates will be put towards covering various costs outlined here: http://www.pyconuk.org/sponsorship/ (e.g. three breakfasts) or support for radically reduced rates for students, the un-waged and those on a low income.

If the above sounds like it'd be appropriate can we turn this information into an email to the PSF..? Happy to draft this and ping you an email.

**Comment by nceder** [comment]
Yes, I'd include those breakdowns in the email.

I assume you've seen this, but the guidelines on a grant proposal are here: https://www.python.org/psf/grants/

It definitely smooths the process of those points are covered. Also we might send one or more of those components to the Outreach and Education committee. However, I have no idea what it's status is at the moment.

But yes, please feel free to ping with a draft.

**Comment by ntoll** [comment]
An email was sent to the PSF today. Please see the PyConUK admin list for a copy.
