### ISSUE TITLE
Write a Visa letter for attendee

### ISSUE THREAD

**Issue by ghickman** [PyconUK/planning2015#73]
Raising on behalf of Mary.

An attendee needs a letter to get a Visa for their flight here.

[Thread for context](https://mail.python.org/mailman/private/pyconuk-adm/2015-June/003320.html).

**Comment by holdenweb** [comment]
Here's a letter I wrote for a DjangoCon 2014 delegate so he could obtain a visa from his local American consulate/embassy. I make no representation to understand the requirements of the UK government having been a stranger to these shores this last twenty years, but I hope it will make an apparently onerous task suddenly seem easier. I tried to attach the PDF version but Github wouldn't have it. Ask by email if you want to see it. Please respect the personal information it contains.

If you want to use my name I'm OK with that - time I did _something_, I suppose.

Tuesday, August 5, 2014
To Whom It May Concern:
I write to confirm the invitation of Moayad Mardini, of HALAJ - ALPAKISTAN
ST., DAMASCUS, SYRIA, to visit the United States of America to participate in the
DjangoCon US 2014 conference in Portland, Oregon, in September 2014.
Moayad is my colleague in the global group of programmers and developers who
work on Django, a web application framework and program. Development
normally takes place over the Internet but we are planning a conference to bring
participants together to discuss their work. The Open Bastion is producing this
conference for the Django Software Foundation in Portland on September 1-6,
2014. We also use Django.
Moayad will be giving a presentation entitled “Medical-level software quality: How
I relied on Django to improve medical research” while at the conference. Speakers at
DjangoCon are not paid. We sometimes help with their travel and
accommodation, but they do not receive any remuneration.
Moayad has arranged to stay at the Hilton Portland and Executive Tower (the site
of the conference) during his stay in the USA. While here, Moayad will be
responsible for his own living expenses.
If you have any further questions regarding Moayad and his visit, please feel free to
contact me directly at +1 571 484 6266 or by email at the address above.
Sincerely,
Steve Holden
FBCS, CITP, MIEEE

**Comment by moonmar** [comment]
I have drafted a very short version of a To Whom It May Concern letter.

I do not know the gentleman concerned and the linguistics conference he attended last year doesn't appear, on the face of it, to be associated by Python.

Does anyone know him?

TO WHOM IT MAY CONCERN

This letter is to confirm that Ibrahim Mubarak is a registered delegate for the Pycon UK 2015 Conference.

The conference will be held at Coventry University Technocentre, Coventry from 18 -21 September 2015.

For further information please visit the website ******\* or contact us at *****@^^^^
