### ISSUE TITLE
Delete old website repo

### ISSUE THREAD

**Issue by snim2** [PyconUK/planning2015#75]
The old [pyconuk.github.io](https://github.com/PyconUK/pyconuk.github.io) doesn't seem necessary any more. The version control history was carefully moved over and the new site is working really well. Would it be less confusing for new people if we just delete the old repo? I think so... If people really want to keep it around "just in case" I have some private repositories on another account that we could use to stash it.

**Comment by d0ugal** [comment]
If you want to keep the history, and make it available. Just do a commit that deletes all the files other than the README.

**Comment by ghickman** [comment]
I've found prefixing the github repo name with `__LEGACY__` or something equally noteworthy has worked well for me in the past. However @d0ugal's suggestion might be more obvious on first glance as GitHub will auto redirect to new urls?
