### ISSUE TITLE
Redirection required for uk.pycon.org

### ISSUE THREAD

**Issue by holdenweb** [PyconUK/planning2015#76]
It appears as though this domain used to point to Github pages of some sort. Since *.pycon.org is the canonical name for PyCon events, it would be best if we could have it as a CNAME for the existing site.

**Comment by inglesp** [comment]
@holdenweb -- good idea.  Would you be able to make this happen?

**Comment by holdenweb** [comment]
I think so. I'll contact Marc-André Lemburg, who administers the pycon.org domain.  S

**Comment by inglesp** [comment]
Thanks Steve -- let us know when you've made some progress.

**Comment by holdenweb** [comment]
Request sent today.

**Comment by holdenweb** [comment]
Correspondence with Marc-André Lemburg: it seems that there's already a CNAME pointer to pyconuk.org from uk.pycon.org. The issue is that Github's server doesn't know to serve that domain, so is presumably rejecting the requests. Github pages for the win. Not.

On 07.09.2015 15:46, Steve Holden wrote:
Hi Marc-André,

PyCon UK is currently running under pyconuk.org. Would it be possible to register uk.pycon.org as a CNAME for that name, please?

It's been CNAMEd like that for many many years :-)

The problem is that their web server (apparently GitHub) is not
configured to recognize this name and thus gives a 404.

Also: I'm not sure whether GitHub pages can have more than one
CNAME associated with them, so this may be a technical issue,
since they already use pyconuk.org as CNAME.

**Comment by inglesp** [comment]
Thanks @holdenweb -- sounds like there's nothing we can do about it this year.

**Comment by holdenweb** [comment]
But it's something we should definitely look into - I really don't
understand why we have to use Github pages, but I'm sure there was a
sensible reason for it.  S

On 16 September 2015 at 18:21, Peter Inglesby notifications@github.com
wrote:

> Thanks @holdenweb https://github.com/holdenweb -- sounds like there's
> nothing we can do about it this year.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/planning2015/issues/76#issuecomment-140810863
> .

## 

Steve Holden
Senior Developer Advocate

**Comment by inglesp** [comment]
I don't really want to get into a debate about the merits of GitHub Pages tonight when there's so much else to do -- except to say that it's been fantastic to see how many people have contributed to the website this year in a way that simply hasn't been possible before.  Not being able to redirect from uk.pycon.org seems a pretty minor inconvenience.

**Comment by holdenweb** [comment]
No need to convinve me - I'm not  great believer in revisiting done deals.
 S

On 16 September 2015 at 18:46, Peter Inglesby notifications@github.com
wrote:

> I don't really want to get into a debate about the merits of GitHub Pages
> tonight when there's so much else to do -- except to say that it's been
> fantastic to see how many people have contributed to the website this year
> in a way that simply hasn't been possible before. Not being able to
> redirect from uk.pycon.org seems a pretty minor inconvenience.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/planning2015/issues/76#issuecomment-140816806
> .

## 

Steve Holden
Senior Developer Advocate
