### ISSUE TITLE
Decide What Needs To Be Bought, eg lanyards

### ISSUE THREAD

**Issue by moonmar** [PyconUK/planning2015#78]
Now that the cost of the conference venue hire and food is covered we can think about ordering:

t-shirts
mugs
badges and lanyards
swag bags
audio video services

What else?

**Comment by inglesp** [comment]
Hi @moonmar -- this is terrific, thanks.  I'm creating issues for each of these, but we should keep this one open for brainstorming purposes.

**Comment by ntoll** [comment]
I think we agreed not to have video services this year except for a "live link" from the main hall to the overflow room.

**Comment by moonmar** [comment]
We have 177 lanyards left over from last year so we need to order 325 plus 500 badge holders

**Comment by holdenweb** [comment]
Do we plan to give speakers a gift? It's a nice way to say "thank you" and they don't need to be horrendously expensive: just some piece of swag that only speakers get.

If we could at least do decent audio, this could be listened to in conjunction with the slides. Pity there'll be no videos - that's a lot of useful information going to waste

**Comment by moonmar** [comment]
Gifts:  I am not sure we have.  A box of Cadbury's Dairy Milk Chocolates comes to mind.  Inexpensive and local.

**Comment by inglesp** [comment]
I think it's been decided on the mailing list that we're not going to get gifts for speakers.

I think everything else has been covered -- @moonmar, is that right?

**Comment by moonmar** [comment]
Mugs, lanyards/badge holders, swag bags ordered.

T-shirts being sorted (artwork to be resolved)

**Comment by inglesp** [comment]
Sounds like this is done then, thanks @moonmar.
