### ISSUE TITLE
Make decision on t-shirts

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#79]
We need to think about conference t-shirts!

Everybody should read http://theagileadmin.com/2015/06/18/shirtops-how-to-make-t-shirts-for-tech-conferences-that-people-actually-wear/ and http://geekfeminism.wikia.com/wiki/T-shirts.

One question: do we actually need t-shirts?  I know quite a few people who never wear their shirts, and I sometimes think it's wasteful of both budget and the environment to make shirts for everyone.

Two alternatives:
- Skip t-shirts entirely this year
- Allow people to order a t-shirt if they want one

Thoughts?

**Comment by ntoll** [comment]
Summary of the bikeshedding on the mailing list: we use yellow, blue and red as colours to designate attendee type (team, community, regular).

Because I like shaving yaks, I suggested the following code to appear on them:

```
from pyconuk import carry_on

calm = True
while calm:
    carry_on()
```

**Comment by ntoll** [comment]
Also, I believe it's a bit late to ask attendees if they want a t-shirt (or not). That should've been on the ticket form. :-(

Something to look at for next year..?

**Comment by ghickman** [comment]
As somewhat of a conference/sponsor t-shirt hoarder I definitely understand and agree with them being quite wasteful (the local charity shops do fairly well from them round here). However I think Nicholas has nailed the situation on the head with it being too late to ask attendees about them for this year. Next year we could design them before tickets go out so attendees can decide if they want them when booking their ticket?

@ntoll – Will we be including installation instructions on the t-shirt too? :trollface:

**Comment by inglesp** [comment]
At Monday's meeting, there was a bit of concern that this trope has been "over-memed", but we've had no other suggestions.

If anybody has other ideas, this is the place to make suggestions.  This kind of thing can get quite bikesheddy quite quickly, so I'd like to put a time limit on discussions here: if we don't appear to have reached a consensus by Friday 24th July, we should have a vote.

**Comment by moonmar** [comment]
We need to have a vote because we need to get graphics ready for the t-shirt order.

Please vote on whatever the options were - I can't remember.

**Comment by inglesp** [comment]
The shirts have been designed and ordered.
