### ISSUE TITLE
Design and order mugs

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#80]
We need to design and order mugs!

(The same arguments could be made about not having mugs as for not having t-shirts, but I think the mugs are something that we do pretty well and are distinctive to the conference, so I'd vote to continue providing them.)

What needs to happen next?

**Comment by inglesp** [comment]
@hawkz, @moonmar, what's the latest on this?

**Comment by moonmar** [comment]
Done and dusted.
