### ISSUE TITLE
Design and order swag bags

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#81]
We need to design and order swag bags!

What needs to happen next?

**Comment by moonmar** [comment]
I have added Steve Hawk to this because he needs to see the image on the bag.

**Comment by hawkz** [comment]
Great - what do you need? Same spec as last year? do we have any sponsor graphics to include?

**Comment by moonmar** [comment]
Same spec as last year.  Someone has offered sponsorship for the swag bag but I cannot remember who.  Nicholas might know.

**Comment by inglesp** [comment]
@hawkz, @moonmar, have these been ordered yet?

**Comment by moonmar** [comment]
Swag bags have been ordered and artwork sent to Heart of England.
