### ISSUE TITLE
Brochure

### ISSUE THREAD

**Issue by zeth** [PyconUK/planning2015#84]
This can wait until a little further down the line but I write the issue so I remember.

Since we are with it quite early this year and a few people expressed a desire for dead tree program; maybe we should go all out and have a delegate brouchure?

Since the talks and schedule are in RST, there is rst2pdf and other tools that help us make a pdf without too much hassle.

Main question would be:
1. How much does it cost and can we afford it?

Parts of the brouchure would probably include:
- Colourful Cover
- Welcome message
- Schedule
- Abstracts
- Delegate List
- Sponsor List
- Other things that I haven't thought of

**Comment by inglesp** [comment]
@zeth, is this going to happen?

**Comment by snim2** [comment]
If not, we should move this to the Planning 2016 repo

**Comment by zeth** [comment]
Well the biggest dependency was to make the schedule 80 columns so that
rst2pdf would not choke on it which we have done. We also have Moreati's
non-tabular version, so it is not impossible that we make a brochure
version.

**Comment by inglesp** [comment]
So @zeth, is this going to happen?

**Comment by zeth** [comment]
Probably not, to be honest I am not keen enough on it to do it myself since
I have too many PyCon UK balls juggling already, made a message to the
list. Probably can close it.
