### ISSUE TITLE
Set up sponsors' booths

### ISSUE THREAD

**Issue by moonmar** [PyconUK/planning2015#86]
Some sponsors want a table to plonk their wares, others want pop up banners.  We need to work out where they can go.

Also Transcode and Django Girls will be located in the space at the stairwell on the first floor.

**Comment by inglesp** [comment]
@moonmar, what needs doing here?

**Comment by moonmar** [comment]
Identify which sponsors want 

tables
pop up banners 

Do they need power?  

Find places to put them. 

If we can ditch the big MAC screens near the John Siddeley room (CC 2.1) that would release two more options.

**Comment by inglesp** [comment]
I'll contact sponsors this week and find out exactly what they need.

**Comment by inglesp** [comment]
We're expecting the following to take up booths:
- Pluralsight
- Nephila/Divio
- Osper
- 2nd Quadrant
- Cobe.io

None have asked for anything more exotic than a table and a power socket.
