### ISSUE TITLE
Move stuff from the Mooney garage to venue

### ISSUE THREAD

**Issue by snim2** [PyconUK/planning2015#87]
Someone with a large car is required to help move boxes of swag and PyCon UK kit from storage to the venue.

**Comment by inglesp** [comment]
@moonmar, have you had any volunteers for this?

**Comment by moonmar** [comment]
err, no.

**Comment by moreati** [comment]
My car isn't large, but we'll see on Sunday if it's doable in 1-3 trips

**Comment by moonmar** [comment]
Hi Alex. I wasn't suggested we move stuff this Sunday - just count things
so we know how much new stock needs to be ordered.

M

**Comment by moreati** [comment]
Sorry, I meant: I volunteer to move things when the time comes, provided it won't take too many trips. I'll see on Sunday how many trips that is likely to be.

**Comment by moonmar** [comment]
Noted Alex and others.

_Mary_
_Mobile_ - +44 (0) 7857 373727

**Comment by moreati** [comment]
The current inventory (plus expected purchases) will easily fit in my car.

The swag is yet to arrive. IIRC the swag last year filled my car plus an escort van, if that's being delivered to Mary's garage we'll need additional arrangements.

**Comment by moonmar** [comment]
Swag is going direct to conference venue

**Comment by inglesp** [comment]
@moonmar -- does this mean that there's nothing left to track with this issue?

**Comment by moonmar** [comment]
All sorted. Alex and Mary moving stuff to venue tomorrow (Thursday)
