### ISSUE TITLE
Plug poster sessions

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#88]
We can all do this, but @nceder volunteered during the meeting.

@nceder, do you have/want access to the twitter account?

**Comment by nceder** [comment]
Yes, I sent two posts to the Python UK list a couple of days ago:

https://mail.python.org/pipermail/python-uk/2015-July/003774.html
https://mail.python.org/pipermail/python-uk/2015-July/003776.html

So I was hoping someone would propagate those. I don't know that I need
access to the twitter account myself - I'll tweet it from my accounts, and
if someone else could tweet from the PyCon UK account, that would be ace.

Cheers,
Naomi

On 17 July 2015 at 19:26, Peter Inglesby notifications@github.com wrote:

> Assigned #88 https://github.com/PyconUK/planning2015/issues/88 to
> @nceder https://github.com/nceder.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/planning2015/issues/88#event-358776807.

## 

Naomi Ceder
https://plus.google.com/u/0/111396744045017339164/about

**Comment by ntoll** [comment]
Cheers! :-)
