### ISSUE TITLE
Share plans for relay to overflow room and recording of talks

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#92]
In Monday's meeting, it seemed like @zeth has made some plans for both relaying audio/video from the main room to the overflow room, and for recording talks more generally.

I think @lukestanley also has had some thoughts here.

Over to you two.

**Comment by zeth** [comment]
Well we do have plans for overflow.

We don't have plans for recording of talks yet. Especially outside the main room.

**Comment by inglesp** [comment]
@zeth, what's the latest on this?

**Comment by inglesp** [comment]
Plans have been shared on the mailing list.
