### ISSUE TITLE
Produce seating plan for dinner

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#93]

**Comment by inglesp** [comment]
Could we have a volunteer to do this?

**Comment by snim2** [comment]
In the past we have used a script which John had. Perhaps someone has a copy... ?

**Comment by inglesp** [comment]
I don't think the script is the difficult bit!

This has been discussed a little on the mailing list under the "Badge Logistics" thread.  @bloodearnest, since you're working on badges, could you take this on too?

**Comment by inglesp** [comment]
@bloodearnest -- how's this looking?

**Comment by bloodearnest** [comment]
Finishing it tonight, planned output is a google doc that can be printed.

On 16 September 2015 at 18:15, Peter Inglesby notifications@github.com
wrote:

> @bloodearnest https://github.com/bloodearnest -- how's this looking?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/planning2015/issues/93#issuecomment-140809212
> .

## 

Simon

**Comment by ghickman** [comment]
Dinner was eaten, seats were found. Good job everyone involved!
