### ISSUE TITLE
Organise badges

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#94]
Assigning to @ntoll in the first instance, since he's got a cunning plan for this.

**Comment by moonmar** [comment]
Found about 200 badge holders.  Takes document 8.5 x 6 cm comfortably.

**Comment by inglesp** [comment]
This has been delegated to @jonathanfine, Steve (Holden) and Simon.

**Comment by bloodearnest** [comment]
Yo, this is me on github, feel free to assign away,

**Comment by moonmar** [comment]
Steve Ha, Simon and Jonathan seem to have this in hand.  I believe Jonathan is printing and I will be folding and stuffing on Thursday, at the venue.  Lanyards and badge holders have been delivered to the Venue.

**Comment by inglesp** [comment]
From the sounds of the mailing list, this is done.
