### ISSUE TITLE
Agenda Items

### ISSUE THREAD

**Issue by zeth** [PyconUK/planning2015#99]
Please give me your agenda items here and I will make sure there are in the AGM announcement.

Agenda annoucement to go Sept 1st so put them here before that.

**Comment by zeth** [comment]
- Statements from Chair
- Statement from Treasurer
- Presentation of New Financial Support Plan
- Statement on Diversity
- Statement on Educational Outreach 
- Future co-operation with PSF
- PyCon UK 2016
- Constitutional Amnedments:
  - Proposal to add promotion of diversity as an aim of the society
  - Proposal to add educational mission as aim of the society
  - Other proposals
- Election of 10 commitee members
- Other things people have already sent me and need to be pulled out of Email

**Comment by zeth** [comment]
Note here is the script from the John era:
https://github.com/PyconUK/planning2015/issues/49

**Comment by snim2** [comment]
This agenda has been transcribed here:

https://github.com/PyconUK/PyConUKSociety/blob/master/agm_agendas/2015AGM_agenda.md

So any changes should be made on that repo via PR (and merged by @zeth)

**Comment by zeth** [comment]
Perfect.
